package com.wallet.digital_wallet.service;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;

import jakarta.mail.internet.MimeMessage;

/**
 * Thin wrapper around Spring's JavaMailSender.
 *
 * The one rule every method here follows: EMAIL SENDING MUST NEVER BREAK
 * THE CALLER. Registration, OTP generation, and transactions all need to
 * succeed even if the mail server is down, misconfigured, or the person's
 * email address bounces. Every send is wrapped in try/catch that only
 * logs - never rethrows. This mirrors the exact same philosophy the
 * existing AuditEventListener already uses for audit writes.
 *
 * @Async (enabled via @EnableAsync on DigitalWalletApplication) means the
 * caller doesn't wait for the SMTP round-trip either - registration
 * returns to the client immediately, the email goes out on a background
 * thread a moment later.
 *
 * IMPORTANT - @Async placement: it's on sendWelcomeEmail/sendOtpEmail/
 * sendTransactionAlertEmail (the methods callers actually invoke), NOT
 * on the private send() helper. Spring's @Async works via a runtime
 * proxy - it only takes effect when a method is called FROM OUTSIDE the
 * class, through that proxy. A method calling another method on `this`
 * (self-invocation) bypasses the proxy entirely, so @Async on an
 * internally-called helper silently does nothing. This is one of the
 * most common Spring AOP mistakes - worth knowing cold for interviews.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class EmailService {

    private final JavaMailSender mailSender;

    private void send(String to, String subject, String body) {
        if (to == null || to.isBlank()) {
            log.warn("Skipped sending email '{}' — recipient address is blank", subject);
            return;
        }
        try {
            SimpleMailMessage message = new SimpleMailMessage();
            message.setTo(to);
            message.setSubject(subject);
            message.setText(body);
            mailSender.send(message);
            log.info("Email sent: '{}' -> {}", subject, to);
        } catch (Exception ex) {
            // Deliberately broad catch: mail server unreachable, bad
            // credentials, invalid address, timeout — none of these
            // should ever propagate back into a business transaction.
            log.error("Failed to send email '{}' to {}: {}", subject, to, ex.getMessage());
        }
    }

    @Async
    public void sendWelcomeEmail(String to, String fullName) {
        send(to, "Welcome to Digital Wallet!",
                "Hi " + fullName + ",\n\n" +
                        "Your Digital Wallet account has been created successfully. " +
                        "You can now log in and start managing your money.\n\n" +
                        "If you didn't create this account, please ignore this email.\n\n" +
                        "— Digital Wallet Team");
    }

    @Async
    public void sendOtpEmail(String to, String otpCode, long expirationMinutes) {
        send(to, "Your Digital Wallet OTP Code",
                "Your one-time password (OTP) to confirm this transfer is:\n\n" +
                        "    " + otpCode + "\n\n" +
                        "This code expires in " + expirationMinutes + " minutes. " +
                        "If you didn't request this transfer, do not share this code with anyone.\n\n" +
                        "— Digital Wallet Team");
    }

    @Async
    public void sendTransactionAlertEmail(String to, String action, String amount,
                                          String walletNumber, String counterparty) {
        String counterpartyLine = counterparty != null
                ? "\nOther wallet: " + counterparty
                : "";
        send(to, "Transaction Alert: " + action,
                "A " + action + " of amount " + amount + " occurred on your wallet " +
                        walletNumber + "." + counterpartyLine +
                        "\n\nIf this wasn't you, please contact support immediately.\n\n" +
                        "— Digital Wallet Team");
    }

    /**
     * Same "never break the caller" rule as send(), but built on
     * MimeMessage/MimeMessageHelper instead of SimpleMailMessage, since
     * SimpleMailMessage can't carry attachments. Used by
     * MonthlyStatementScheduler (Feature #7) to email the PDF statement
     * generated by StatementService (Feature #4) directly, rather than
     * just linking to it.
     */
    @Async
    public void sendEmailWithAttachment(String to, String subject, String body,
                                        byte[] attachment, String attachmentFilename) {
        if (to == null || to.isBlank()) {
            log.warn("Skipped sending email '{}' — recipient address is blank", subject);
            return;
        }
        try {
            MimeMessage mimeMessage = mailSender.createMimeMessage();
            // 'true' = multipart, required for attachments
            MimeMessageHelper helper = new MimeMessageHelper(mimeMessage, true);
            helper.setTo(to);
            helper.setSubject(subject);
            helper.setText(body);
            helper.addAttachment(attachmentFilename, new org.springframework.core.io.ByteArrayResource(attachment));

            mailSender.send(mimeMessage);
            log.info("Email with attachment sent: '{}' -> {}", subject, to);
        } catch (Exception ex) {
            log.error("Failed to send email with attachment '{}' to {}: {}", subject, to, ex.getMessage());
        }
    }
}
